apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-cpp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-cpp-app
  template:
    metadata:
      labels:
        app: cpu-cpp-app
    spec:
      containers:
      - name: cpu-cpp-app
        image: cpu-cpp-app:latest
        imagePullPolicy: IfNotPresent
